### ISSUE TITLE
In place bag creation

### ISSUE THREAD

**Issue by pwinckles** [jscancella/bagging#45]
@jscancella Thanks for maintaining this library!

I was just working on using it to create some bags. The problem I encountered is that it is designed to create a bag by making copies of all of the payload files. For my use case, I do not want this duplication.

I browsed the code, and it looks like it would be fairly easy to support either creating bags in place or optionally allowing moves instead of copies.

For creating bags in place, I believe the only modification that would be needed is a check to see if the `entry` and `newEntry` physical locations are the same ([here](https://github.com/jscancella/bagging/blob/master/src/main/java/com/github/jscancella/domain/Bag.java#L403)) and do nothing if they are. However, I see that you have a warning [here](https://github.com/jscancella/bagging/blob/master/src/main/java/com/github/jscancella/domain/Bag.java#L323) that would fire if you did try to create the bag in place. The warning text suggests that it won't create the bag, but it doesn't actually appear to short circuit.

If you don't like the idea of creating a bag in place, then perhaps moves could be supported? You could have an optional option either at the builder level or at the payload file level to indicate if files should be moved or copied. A slightly larger change, but perhaps more in line with how you intend the builder to be used?

If you are amenable to either of these ideas, I'd be happy to send you a PR, if you'd like.

**Comment by jscancella** [comment]
@pwinckles thank you for the kinds words. With the understanding of what a bag is for (https://github.com/jscancella/bagging#what-is-a-bag), my first reaction is "why do you need to make a bag in place?". 

You mention 
> For my use case, I do not want this duplication.

But you don't explain what that use case is, could you elaborate? One of the reasons I don't care for "bag in place" is because you have to move them into a data directory which I have seen cause corruption (or other) problems and then you have to spend time recovering the files before you can try and bag again. Again, I am not totally against it, but there needs to be an overwhelming reason to add it.

**Comment by pwinckles** [comment]
Sure, the use case here is that we intend to use bag to disseminate objects from our preservation storage. In order to do this, first the contents of the objects are retrieved from storage and written to a local mount; then the objects are bagged and zipped. I don't want a copy for two reasons. 

1. I have no need to keep the source files after bagging and don't need the files to be recoverable.
2. It's wasteful of time and space to make an unneeded copy.

**Comment by jscancella** [comment]
Does your preservation storage not provide an interface that is compatible with Java `Path` api(https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html)?

**Comment by jscancella** [comment]
What does OCFL stand for? Doing a web search I just keep getting Orange County related findings...

**Comment by pwinckles** [comment]
Sorry, I should have included a link.

https://ocfl.io/

**Comment by jscancella** [comment]
OCFL looks like just a certain file structure layout. Your cloud storage should provide an API for directly accessing the files. For example,  AWS has https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-s3-objects.html#download-object which returns a `S3ObjectInputStream`. I would prefer to add streams as an input and have it use something like `Files.copy(is, Paths.get(filePath));` instead of `Files.copy(entry.getPhysicalLocation(), newEntry.getPhysicalLocation(), StandardCopyOption.REPLACE_EXISTING);`

**Comment by pwinckles** [comment]
An API for adding streams would work, though it is slightly more work to use. Instead of just adding a directory to the bag, I'd have to iterate over each stream, construct the `data` relative location it should be inserted at, and add it to the bag.

Would you parallelize the streaming to disk or write each stream serially? The OCFL client that we're using does have the ability to either return lazy-loading streams to object content files or reconstruct an object on disk. The former is primarily useful if you only want access to a subset of files within an object; while the later is more useful if you want the entire object, the client handles the parallelization and file validation.

**Comment by jscancella** [comment]
Parallelization with file IO is often not worth while as it depends on the storage's make transfer speed. For example, if you are using a 7200RPM spinning disk, there isn't a point to parallelize because CPU isn't the bottleneck, it is the data transfer. But if on the other hand you have a RAM disk or Optane disk that is using PCI-e 4, you might see enough of a performance gain to make the overhead of parallelizing worth while (only testing would tell).

I look forward to your pull request that adds `inputstream` to the `BagBuilder.add()` method.

**Comment by pwinckles** [comment]
Hmm... It's been a while since I did performance testing on the OCFL client (certainly need to do a fresh round), but in the past I was seeing some performance gains in parallelizing some IO operations, up to a point. But, I agree that it is largely circumstantial, and likely doesn't matter that much, especially given some other constraints I'm working with here.

I'll put a streaming PR together shortly. Thanks!

**Comment by pwinckles** [comment]
I just started looking into adding the API for adding `InputStreams` to bags, and it's actually a fairly extensive refactor that is starting to make me feel a little uncomfortable doing in someone else's codebase.

The initial `Manifests` are constructed prior to creating the `data` directory. `ManifestEntries` are later used to copy content into `data`, and `ManifestEntries` only have the concept of a `Path`. Furthermore, `Hasher` only operates on `Paths` as well, and when the initial manifests are created, prior to calling `bag.write()`, the entry digests are unknown. This is not so much a problem because another `Manifest` is generated later that could include the digests, but it does make things a lot more complicated.

Presumably, `ManifestEntry` would need to wrap the original `InputStream` in a `DigestInputStream`, which would need a custom implementation to integrate with `Hasher`, and then retrieve the digest after the stream has been written to disk. The problem is complicated by the fact that multiple digest algorithms could be used, and the `InputStream` would need to be wrapped with a `DigestInputStream` for each algorithm in a nested fashion. Any given `ManifestEntry` would need to have both a handle for the outermost wrapping, as well as a way to retrieve the appropriate digest after the stream is closed.

When the bag is written, the first `ManifestEntry` that contains a stream that has not yet been written, would be responsible for writing the file to disk, and subsequent entries for the same file would simply lookup their now computed digests.

Tangentially related, I believe there is a bug [here](https://github.com/pwinckles/bagging/blob/master/src/main/java/com/github/jscancella/domain/Bag.java#L403) in the existing code when it constructs bags that use multiple digest algorithms. Because the `ManifestEntries` drive the population of the `data` directory, it will copy every file once per `Manifest` instead of once per bag.

**Comment by jscancella** [comment]
>...it's actually a fairly extensive refactor...

Yes. As I said earlier, we have to have a shared understanding of what a bag is - to me and the other authors of the BagIt specification it is files on disk meant for transfer. That is why the refactor is so hard, you are fighting against the design of the library and the specification.

As for the bug, yes it is sub-optimal but you have to remember that only since BagIt specification 1.0 has there been the direct requirement to list all files in all manifests. I have personally witnessed bags that only some of the files were listed in the MD5 hash and some in the SHA1 hash manifests... Take a look at https://github.com/LibraryOfCongress/bagit-conformance-suite as it covers all of the many edge cases that are allowed but are strange. Any BagIt library needs to support the valid bags.

Why don't you try and do the `bag in place` PR like your originally proposed, perhaps you can make it nice and clean as well as provide tests that ensure it is working correctly?

**Comment by pwinckles** [comment]
Ha! I was just about to comment that I could create a PR for [this commit](https://github.com/pwinckles/bagging/commit/d4daaf4d150f7c9c22a9444252681ec5131676aa), but I wasn't sure if you were okay with that behavior. Looks like you are. :)

:+1:

**Comment by jscancella** [comment]
> 
> 
> Ha! I was just about to comment that I could create a PR for [this commit](https://github.com/pwinckles/bagging/commit/d4daaf4d150f7c9c22a9444252681ec5131676aa), but I wasn't sure if you were okay with that behavior. Looks like you are. :)
> 
> 👍

I am for the most part. Ideally we should make sure that the checksums match before skipping as their might be a name clash among the manifests, but I am not sure the performance hit is worth catching that edge case.

**Comment by jscancella** [comment]
I think this is OBE with https://github.com/jscancella/bagging/commit/c431a49340f5a21a9362acfb06c1bdf12f82a187? If not, please reopen the issue
