### ISSUE TITLE
Spell and grammer check 

### ISSUE THREAD

**Issue by jscancella** [jscancella/bagging#5]
Have someone look over and review README.md for spelling, grammer, and other mistakes.

**Comment by bhimak** [comment]
@jscancella  Can I claim this?

**Comment by jscancella** [comment]
Sure, just send a pull request when you are ready for it to be merged. Thanks for the help!

**Comment by bhimak** [comment]
#7

**Comment by Jaspervv** [comment]
**grammer** aficionados  
**grammar** aficionados

Usually this is due to the amount of files being **transfered** is very large
Usually this is due to the amount of files being **transferred** is very large

as well as **cononical** basic bags for each specification version
as well as **canonical** basic bags for each specification version
